---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tinytale/public_html/
    - /bin/rsync -av --delete --exclude=.git --exclude=.cpanel.yml --exclude=.gitignore --exclude=node_modules --exclude=dist ./ "$DEPLOYPATH"
    - /bin/find "$DEPLOYPATH" -type d -exec chmod 755 {} \;
    - /bin/find "$DEPLOYPATH" -type f -exec chmod 644 {} \;
    - /bin/chmod 755 "$DEPLOYPATH"*.php 2>/dev/null || true
